[build]
builder = "NIXPACKS"
buildCommand = "npm run build"
watchPatterns = ["src/**", "public/**"]
publishDir = "dist"

[deploy]
startCommand = "npx serve -s dist"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
