[phases.setup]
nixPkgs = ['nodejs', 'postgresql']

[phases.install]
cmds = [
    'npm install',
    'cd frontend && npm install',
    'cd backend && npm install'
]

[phases.build]
cmds = [
    'cd frontend && npm run build',
    'cd backend && npm run build'
]

[start]
cmd = 'cd backend && npm start'

[deploy]
startCommand = 'cd backend && npm start'
restartPolicyType = 'ON_FAILURE'
restartPolicyMaxRetries = 10
healthcheckPath = '/api/health'
healthcheckTimeout = 300
