version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: windsurf_events
      POSTGRES_USER: windsurf
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: 
      context: ../backend
      dockerfile: ../infra/Dockerfile.backend
    environment:
      DATABASE_URL: postgresql://windsurf:${DB_PASSWORD}@postgres:5432/windsurf_events
      NODE_ENV: production
      PORT: 3000
    depends_on:
      - postgres
    ports:
      - "3000:3000"

  frontend:
    build:
      context: ../frontend
      dockerfile: ../infra/Dockerfile.frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data:
